### ISSUE TITLE
Root card tokenization

### ISSUE THREAD

**Issue by mjallday** [balanced/balanced-js#10]
The current version of balanced.js works like this:
1. initialize library
2. tokenize a card

We're streamlining this process by allowing cards to be tokenized at the root level (e.g. they will POST to `api.balancedpayments.com/cards` (not routed under marketplace).

We need to change the balanced.js library to handle this. There should be no more `init` call. 

This must be completely tested.

Questions:
1. Should we maintain the init method for backwards compatibility or should this be a new version?

**Comment by matthewfl** [comment]
My two cents on this is that I think we should also support tokenizing cards using jsonp.  That way we will not have to maintain complex cors support for older browsers and I imaging that the code will be less than 100 lines (~25 lines for making the request, and what ever client side checking logic).

The request would look something like `https://api.balancedpayments.com/cards?callback=asdfadsf&data=urlencode(JSON.stringify(data_for_request))`
Or we could make a separate end point just for the jsonp: `https://api.balancedpayments.com/jsonp?type=(card|bank_account)&callback=asdfasdf&data=urlencode(JSON.stringify(data_for_request)`

http://www.erikzaadi.com/2012/07/16/jquery-compatible-jsonp-with-nginx/

**Comment by mjallday** [comment]
That's a great idea, can you make it a separate issue? Given our timeline I don't think we'll get it done in our initial sprint since we'd need to also extend midlr and also figure out how to sanitize the logs. You're right tho, +1 for simplicitly.

**Comment by matthewfl** [comment]
All the functionality for jsonp can be implement in the nginx config.  It can internally rewrite the request to be a post request

You would also have to turn off logging the url for these endpoints as they would contain card data (but that is still nginx config stuff)

**Comment by mahmoudimus** [comment]
yep :) we should definitely enable jsonp support.
