### ISSUE TITLE
Add helper function to validate routing number checksum for ACH API

### ISSUE THREAD

**Issue by matin** [balanced/balanced-js#2]
All bank account routing numbers must follow the [MICR routing number format](http://en.wikipedia.org/wiki/Routing_transit_number#MICR_Routing_number_format), which can be validated client side.

The helper function already exists in the `v1` version of balanced.js.

**Comment by mjallday** [comment]
```
balanced.BankAccount. validateRoutingNumber(routingNumber)
```

Returns `true` or `false` depending on if it passes the mod 10 check.
