### ISSUE TITLE
Support jsonp for tokenization

### ISSUE THREAD

**Issue by matthewfl** [balanced/balanced-js#22]
The request would look something like `https://api.balancedpayments.com/cards?callback=asdfadsf&data=urlencode(JSON.stringify(data_for_request))`
Or we could make a separate end point just for the jsonp: `https://api.balancedpayments.com/jsonp/(cards|bank_accounts)&callback=asdfasdf&data=urlencode(JSON.stringify(data_for_request)`

http://www.erikzaadi.com/2012/07/16/jquery-compatible-jsonp-with-nginx/

Possible nginx config to support this

```
location /jsonp/cards {
            log_format compression '$remote_addr - $remote_user [$time_local] '
                                   '"/jsonp/cards" $status $bytes_sent '
                       '"$http_referer" "$http_user_agent"';
            if ($args_callback) {
            echo_before_body '$args_callback(';
            echo_after_body ');'
            }
        set $upstream_api_url http://midlr_api;
            proxy_method POST;
        proxy_set_header 'Content-type' 'application/json';
        proxy_set_body $args_data;

            proxy_pass $upstream_api_url/cards;
        }
```

**Comment by nodesocket** [comment]
Implemented.
