### ISSUE TITLE
Build number versioning

### ISSUE THREAD

**Issue by mjallday** [balanced/balanced-js#32]
Please tweak the library to build versioned libraries.

they should end up being deployed like this:

`https://js.balancedpayments.com/{major}.{minor}.{build}/balanced.js` where major is the API revision, minor is incremented whenever we change the balanced.js interface in a non-backwards compatible manner and build is incremented anytime we change anything in the library.

**Comment by nodesocket** [comment]
So right now, it uploads in this format to the amazon s3 bucket:

```
upload: [
                    {
                        src: 'build/balanced.js',
                        dest: '<%= pkg.version %>/balanced.js'
                    },
                    {
                        src: 'build/proxy.html',
                        dest: '<%= pkg.version %>/proxy.html'
                    }
                ]
```

We will have to update nginx config in confidence to support this though.

**Comment by nodesocket** [comment]
This should work, the following pull, cleans up the nginx config for liberty significantly.

https://github.com/balanced/confidence/pull/24
