### ISSUE TITLE
Serialization issue with arrays

### ISSUE THREAD

**Issue by mjallday** [balanced/balanced-js#35]
The XD library appears to be incorrectly serializing arrays when passing them from proxy to the balanced.js library. 

Here's what the server returns:

``` js
{
  "cards": [
    {
      "href": "/cards/CC6AmwAOSWiNXW3YVn2Mx14b",
      "id": "CC6AmwAOSWiNXW3YVn2Mx14b",
      "links": {}
    }
  ],
  "links": {}
}
```

Here's what balanced.js spits out:

``` js
{
    "status": 201,
    "data": {
        "cards": {
            "0": {
                "href": "/cards/CC6AmwAOSWiNXW3YVn2Mx14b",
                "id": "CC6AmwAOSWiNXW3YVn2Mx14b"
            }
        }
    }
}
```

If you look closely you'll see that the `cards` collection has changed from a list into a hash.

I suspect the issue lies in the XD deserialization lib but I have not confirmed - https://github.com/balanced/balanced-js/blob/rev1/lib/xd.js#L4

**Comment by mjallday** [comment]
@nodesocket can you take a look at this? it's top priority. you may want to look and see if upgrading the library is feasible - https://github.com/oyvindkinsey/easyXDM/ - try fixing or cherry picking the bug in the encoding code or switching out to JSONP

**Comment by mjallday** [comment]
The example does not work. I get a 404

**Comment by nodesocket** [comment]
Here is brand new clean fiddle, using js version `1.1.1`. Please SKYPE PM and tell them to use this for testing tokenization. Jsfiddle.

**Comment by mjallday** [comment]
+1

**Comment by mjallday** [comment]
@nodesocket two things appear incorrect, I've added separate issues for them, can you knock them out?

https://github.com/balanced/balanced-js/issues/40
https://github.com/balanced/balanced-js/issues/41
