### ISSUE TITLE
rev1 tests are very brittle

### ISSUE THREAD

**Issue by matthewfl** [balanced/balanced-js#43]
In attempting to run tests on linux I have found that the testing framework is very brittle
1. it requires that `google-chrome` be in my path otherwise it crashes, it did not look at the fact that `chromium` is in my path, and it should not fail if someone does not have chrome or firefox not installed.
2. when using `grunt serve` it looks like it tries to make a mac specific `open` call after starting the server, but when that fails the grunt task fails and stops the server

**Comment by nodesocket** [comment]
Should be fixed, removed using `Chrome` explicitly.
