### ISSUE TITLE
Problems with error messages for bank accounts

### ISSUE THREAD

**Issue by patrickyan** [balanced/balanced-js#60]
**Error messages do not all come at the same time.**

If the user forgets to enter name, routing number, or account number, then the errors say those fields are missing. However, balanced.js won't notify of a missing type field until the other 3 fields are filled.

Another problem is that balanced.js won't validate routing numbers until after type is selected (using test numbers from the docs). If this due to different number validations for checking and savings account, please state clearly in the docs.

**Error messages are not consistent**

There are these:

```
 account_number: "Missing field"
 bank_code: ""123" is not a valid bank code"
 name: "Missing field"
```

Then there's this:

```
category_code: "request"
category_type: "request"
description: "Invalid field [type] - "None" must be a string Your request id is OHMc47b762c47af11e3925902a1fe53e539."
extras: Object
request_id: "OHMc47b762c47af11e3925902a1fe53e539"
status: "Bad Request"
status_code: "400"
```

And this:

```
category_code: "invalid-routing-number"
category_type: "request"
description: "Routing number is invalid. Your request id is OHMd2a442ba47af11e3b00702a1fe53e539."
extras: Object
request_id: "OHMd2a442ba47af11e3b00702a1fe53e539"
status: "Bad Request"
status_code: "400"
```

This needs 3 ways to check errors: by checking the key, by searching the description string for [type], and by checking the category_code value.

**Comment by patrickyan** [comment]
It seems like the last two can even be mixed:

```
category_code: "invalid-routing-number"
category_type: "request"
description: "Invalid field [type] - "None" must be a string Your request id is OHMbd82a48047be11e3b00702a1fe53e539."
extras: Object
request_id: "OHMbd82a48047be11e3b00702a1fe53e539"
status: "Bad Request"
status_code: "400"
```

which can be confusing...

**Comment by mjallday** [comment]
This is something that's already been largely addressed in the [revision 1 branch](https://github.com/balanced/balanced-js/issues/41) of balanced.js which now renders an error object that is consistent with what the API returns.

The original balanced.js is unlikely to change since it's about to be deprecated in favour of this new revision. 

If you want to create a pull-request that adds and tests these changes in a way which is backwards compatible you're more than welcome to do so but it's very unlikely we'll back-port these changes.

**Comment by patrickyan** [comment]
I'm just using the one balanced provides in the docs. Is that going to be updated? https://js.balancedpayments.com/v1/balanced.js

**Comment by mjallday** [comment]
No, it will be deprecated and a new version provided.
