### ISSUE TITLE
Can't tokenize card

### ISSUE THREAD

**Issue by tarunc** [balanced/balanced-js#63]
It is trying to make a JSONP request to the api server. It gets a 401 Authorization Required response.

URL:
https://api.balancedpayments.com/jsonp/cards?callback=balanced_jsonp_40716435480862856&data=%7B%22number%22:%224242424242424242%22,%22expiration_month%22:3,%22expiration_year%22:2015,%22security_code%22:%22123%22,%22name%22:%22Tarun%20Chaudhry%22,%22postal_code%22:%2295014%22,%22meta%22:%7B%22capabilities_system_timezone%22:-8,%22capabilities_user_agent%22:%22Mozilla/5.0%20(Macintosh;%20Intel%20Mac%20OS%20X%2010_9_0)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/31.0.1650.57%20Safari/537.36%22,%22capabilities_language%22:%22en-US%22,%22capabilities_kp%22:36,%22capabilities_cli%22:0,%22capabilities_loaded%22:1386294521720,%22capabilities_screen_width%22:1920,%22capabilities_screen_length%22:1080,%22capabilities_hist%22:2,%22capabilities_cookie%22:%221383350633531.36316291126422584.58!0%22,%22capabilities_cl%22:true,%22capabilities_ps%22:true,%22capabilities_submitted%22:1386295111455,%22capabilities_scrollX%22:0,%22capabilities_scrollY%22:0%7D%7D

cURL:

```
curl 'https://api.balancedpayments.com/jsonp/cards?callback=balanced_jsonp_40716435480862856&data=%7B%22number%22:%224242424242424242%22,%22expiration_month%22:3,%22expiration_year%22:2015,%22security_code%22:%22123%22,%22name%22:%22Tarun%20Chaudhry%22,%22postal_code%22:%2295014%22,%22meta%22:%7B%22capabilities_system_timezone%22:-8,%22capabilities_user_agent%22:%22Mozilla/5.0%20(Macintosh;%20Intel%20Mac%20OS%20X%2010_9_0)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/31.0.1650.57%20Safari/537.36%22,%22capabilities_language%22:%22en-US%22,%22capabilities_kp%22:36,%22capabilities_cli%22:0,%22capabilities_loaded%22:1386294521720,%22capabilities_screen_width%22:1920,%22capabilities_screen_length%22:1080,%22capabilities_hist%22:2,%22capabilities_cookie%22:%221383350633531.36316291126422584.58!0%22,%22capabilities_cl%22:true,%22capabilities_ps%22:true,%22capabilities_submitted%22:1386295111455,%22capabilities_scrollX%22:0,%22capabilities_scrollY%22:0%7D%7D' -H 'Host: api.balancedpayments.com' -H 'Authorization: Basic MY_MARKETPLACE_AUTH' -H 'Cookie: csrftoken=CRSF_TOKEN; existing=1; session=SESSION_COOKIE'
```

Response:
balanced_jsonp_40716435480862856(
{"status":401,"header":{"X-Balanced-Guru":"OHMe84c2f585e1911e3a84c02a1fe53e539","Content-Type":"application\/json","www-authenticate":"Basic realm=\"<p>The server could not verify that you are authorized to access the URL requested.  You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.<\/p><p>In case you are allowed to request the document, please check your user-id and password and try again.<\/p>\"","x-newrelic-app-data":"PxQFWFNXCQYTVVhWAwQDVUYdFhE1AwE2QgNWEVlbQFtcCxY0QwgcAQVEUxJETxgDHERRTAcDBF5TBQYHVlJSWgNRDFsOFBQDA1ABTRFDB1dQBVVQV1RaAFZVUQMEARVKRFdXXxEDPg==","access-control-allow-origin":"*","Content-Length":600,"access-control-allow-headers":"Content-Type","x-balanced-host":"balanced-api-05","access-control-allow-methods":"POST, OPTIONS","X-Midlr-Version":"2","x-balanced-version":"aadda5908f9c6479980e9e4b1fc747ed1255abcb"},"body":"{\n  \"status\": \"Unauthorized\",\n  \"category_code\": \"authentication-required\",\n  \"category_type\": \"permission\",\n  \"description\": \"<p>The server could not verify that you are authorized to access the URL requested.  You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.<\/p><p>In case you are allowed to request the document, please check your user-id and password and try again.<\/p> Your request id is OHMe84c2f585e1911e3a84c02a1fe53e539.\",\n  \"request_id\": \"OHMe84c2f585e1911e3a84c02a1fe53e539\",\n  \"status_code\": 401\n}"}
);

This is from the dashboard.

**Comment by mjallday** [comment]
It seems to work as expected when I run this jsfiddle - http://jsfiddle.net/amcf6/1/

**Comment by tarunc** [comment]
Are you sure you have session cookie set? Its not working for me. I get a GET 200 OK but the when I look at the response, it's status 401.

**Comment by mjallday** [comment]
I do not have a cookie set, cookies are ignored by the API.

copy and pasting your command I get success

`curl 'https://api.balancedpayments.com/jsonp/cards?callback=balanced_jsonp_40716435480862856&data=%7B%22number%22:%224242424242424242%22,%22expiration_month%22:3,%22expiration_year%22:2015,%22security_code%22:%22123%22,%22name%22:%22Tarun%20Chaudhry%22,%22postal_code%22:%2295014%22,%22meta%22:%7B%22capabilities_system_timezone%22:-8,%22capabilities_user_agent%22:%22Mozilla/5.0%20(Macintosh;%20Intel%20Mac%20OS%20X%2010_9_0)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/31.0.1650.57%20Safari/537.36%22,%22capabilities_language%22:%22en-US%22,%22capabilities_kp%22:36,%22capabilities_cli%22:0,%22capabilities_loaded%22:1386294521720,%22capabilities_screen_width%22:1920,%22capabilities_screen_length%22:1080,%22capabilities_hist%22:2,%22capabilities_cookie%22:%221383350633531.36316291126422584.58!0%22,%22capabilities_cl%22:true,%22capabilities_ps%22:true,%22capabilities_submitted%22:1386295111455,%22capabilities_scrollX%22:0,%22capabilities_scrollY%22:0%7D%7D' -H 'Host: api.balancedpayments.com' -H 'Authorization: Basic MY_MARKETPLACE_AUTH' -H 'Cookie: csrftoken=CRSF_TOKEN; existing=1; session=SESSION_COOKIE'`

```
balanced_jsonp_40716435480862856(
{"status":201,"header":{"X-Balanced-Guru":"OHMab89cefc5e2011e3a84c02a1fe53e539","Content-Type":"application\/json","x-newrelic-app-data":"PxQFWFNXCQYTVVhWAwQDVUYdFhE1AwE2QgNWEVlbQFtcCxYxSBVbDQoZVA4IF0pcXAgEEBhSVhQAQhhQEAMCFlVAFEIIFBQCHVUIVAhSAFJXAA9RUlIBCgJWTUIGAQJeSBEUUAAAUVUBUFwEDQtVVwYHAEMdQVUDCEVSPA==","access-control-allow-origin":"*","Content-Length":154,"access-control-allow-headers":"Content-Type","x-balanced-host":"balanced-api-06","access-control-allow-methods":"POST, OPTIONS","X-Midlr-Version":"2","x-balanced-version":"aadda5908f9c6479980e9e4b1fc747ed1255abcb"},"body":"{\n  \"cards\": [\n    {\n      \"href\": \"\/cards\/CC5dHTdwaKIJVQe7rKwykGSP\",\n      \"id\": \"CC5dHTdwaKIJVQe7rKwykGSP\",\n      \"links\": {}\n    }\n  ],\n  \"links\": {}\n}"}
);
```

and adding a card via the dashboard also works as expected for me.

**Comment by tarunc** [comment]
When I don't send the basic authorization, it seems to work.

**Comment by matthewfl** [comment]
the response code on the js file will always be 200 otherwise the browser will no execute it.

are you saying that you are getting a status: 401 in the body of the response?

**Comment by tarunc** [comment]
@matthewfl Yup, the response says status 401

The request completes successfully with a 200.

**Comment by mjallday** [comment]
what's setting the basic auth? api uses basic auth but dashboard uses cookies for auth.

**Comment by tarunc** [comment]
My browser is just passing basic auth with the request (even the jsfiddle request), its passing basic auth in.

It works if I go to the url directly: https://api.balancedpayments.com/jsonp/cards?callback=23&data=%7B%22number%22:%224111111111111111%22,%22expiration_month%22:%2212%22,%22expiration_year%22:%222020%22,%22security_code%22:%22123%22,%22meta%22:%7B%22capabilities_system_timezone%22:-8,%22capabilities_user_agent%22:%22Mozilla/5.0%20(Macintosh;%20Intel%20Mac%20OS%20X%2010_9_0)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/31.0.1650.57%20Safari/537.36%22,%22capabilities_language%22:%22en-US%22,%22capabilities_kp%22:0,%22capabilities_cli%22:1,%22capabilities_loaded%22:1386297932546,%22capabilities_screen_width%22:1920,%22capabilities_screen_length%22:1080,%22capabilities_hist%22:1,%22capabilities_cookie%22:%221386297593165.16857607220299542.2!0%22,%22capabilities_submitted%22:1386297938043,%22capabilities_scrollX%22:0,%22capabilities_scrollY%22:0%7D%7D

In this case, my browser doesn't pass in basic auth.

Thru a JSONP request, my browser sends basic auth which messes up the API.

**Comment by tarunc** [comment]
It seems like the basic auth credentials are being cached by my browser and Chrome is re-sending those credentials when making the JSONP request. http://www.tolaris.com/2009/09/08/logging-out-of-http-auth-with-firefox/

**Comment by matthewfl** [comment]
we might consider supporting jsonp on the js domain, or having a domain specifically for jsonp to avoid this issue.

I am assuming that there is not a reasonable way to fix it so the dashboard does not set the basic auth for the whole api.bp domain?

**Comment by mjallday** [comment]
I still don't understand what's setting the basic auth. 

The dashboard _does_ set it for requests to the API but if that's the case then the same basic auth creds should work for the request to the JS.

Looking into that request you have this is a invalid API key that you're passing to the API so I'm inclined to say this is not worth fixing. The API would have respected it if you sent valid credentials.

JS on a different domain is a separate issue, feel free to open another issue to discuss that.

**Comment by matthewfl** [comment]
another possible way to prevent this from happening is by just removing the auth header when it is tokenized from the jsonp endpoints.

**Comment by mjallday** [comment]
https://github.com/balanced/confidence/commit/21a7751a5328efc15cfa683005fc9cc22f05c408 - done
