### ISSUE TITLE
Rename isSecurityCodeValid in 1.1

### ISSUE THREAD

**Issue by mjallday** [balanced/balanced-js#70]
@remear pointed out that the `csc` field has been renamed to card verification value (`cvv`) and as such we should change the method to `isCardVerificationValueValid` or `isCVVValid`

**Comment by remear** [comment]
I prefer isCVVValid since it's less verbose.

**Comment by steveklabnik** [comment]
Three Vs in a row makes me cringe, but I guess it's not the worst thing.

**Comment by mjallday** [comment]
Or we rename it to `validateCVV` the same as #71!

**Comment by steveklabnik** [comment]
Making the call: `isCVVValid`.
