### ISSUE TITLE
Validate Account Number Format

### ISSUE THREAD

**Issue by remear** [balanced/balanced-js#8]
Add a validation function to ensure the account number is all digits.

**Comment by mjallday** [comment]
There is no standard for bank account numbers. It's possible (although I haven't seen one yet) to have a valid bank account "number" that contains `A-z`. Routing numbers can be, and are, validated.

**Comment by remear** [comment]
Didn't know that. Thanks. It was suggested in https://github.com/balanced/balanced-docs/issues/64 that we ensure account numbers contain only digits.
