### ISSUE TITLE
Fails to tokenize when '#' is passed into the address line field 

### ISSUE THREAD

**Issue by rserna2010** [balanced/balanced-js#90]
http://jsfiddle.net/an5Cz/20/

Throws a 400 error.

**Comment by blim8183** [comment]
+1

**Comment by matthewfl** [comment]
https://github.com/balanced/balanced-js/blob/rev1/src/balanced.js#L472

I think the issue is that the # isn't being url encoded properly

**Comment by matthewfl** [comment]
this should be fixed now, if not please reopen this issue

**Comment by blim8183** [comment]
It's working for me now, thanks!
