### ISSUE TITLE
Balanced JS lib on Parse.com platform

### ISSUE THREAD

**Issue by sidharthshah** [balanced/balanced-js#93]
Hello, 
         I am developing a Parse app, which requires payment integration. Unfortunately Parse.com doesn't support NPM, because of which I cannot do npm install and get work done. Is there a way to include say a "stand alone" js library which includes all dependencies. Right now its not working because jsonapi-client.js (one of Balanced.js's dependencies) is found to be missing. 

Error: https://gist.github.com/sidharthshah/8a44fce5c8b5bd2c82cb

Any other suggestion would be appreciated.

**Comment by mjallday** [comment]
@rserna2010 can you look into this?

**Comment by matthewfl** [comment]
balanced.js is the client side tokenization system, so I doubt that this is the correct place for this issues

this appears to be the correct issue: https://github.com/balanced/balanced-node/issues/29
