### ISSUE TITLE
Balanced server should be sending the "Vary: Accept-Encoding" header. 

### ISSUE THREAD

**Issue by rootedsoftware** [balanced/balanced-js#97]
When I scanned my webapp on pingdom.com I get this message. 

The following publicly cacheable, compressible resources should have a "Vary: Accept-Encoding" header:
https://js.balancedpayments.com/1.1/balanced.js

I looked it up and here is a good article explaining why this is needed. 
https://www.maxcdn.com/blog/accept-encoding-its-vary-important/

**Comment by mjallday** [comment]
:100: thanks for bringing this to our attention :)

> if a server sends the Vary: User-Agent header, intermediate caches will store a separate cache entry for each User-Agent they see

So essentially this will cause any intermediate caches to store a copy of balanced.js based on the "Accept-Encoding" header which should mean it will cache the gzipped version and the non-gzipped version.

We could add this in the backend nginx config but I believe the easiest way would be to add it to the headers passed through when we upload the file - https://github.com/balanced/balanced-js/blob/rev1/Gruntfile.js#L190
